# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

environment: demo

logging:
  config: classpath:logback-dev.xml

spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    jpa:
      show-sql: true
      properties:
        hibernate.format_sql: true
        hibernate.type: trace
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
    redis:
        host: 106.14.177.129
        password: d8$jjkl902
        maxIdle: 60
        minIdle: 15
        maxTotal: 120
        minEvictableIdleTimeMillis: 900000
        timeBetweenEvictionRunsMillis: 900000
        maxWaitMillis: 5000
        testOnBorrow: true
        port: 6379
        database: 0

    datasource:
        xcode:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/risk
          username: root
          password: 123456
          test-on-borrow: true
          validation-interval: 30
          validation-query: SELECT 1
#          initSQL: "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'"

# ===================================================================
# biz properties
# ===================================================================

#rocketmq:
#  name-server: 10.1.0.33:9876
#  producer:
#    access-key: AK
#    secret-key: SK

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    security:
        encrypt:
            key: dbb6e7c46b5fc376fb8ceed310776523
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: headstartServer@localhost
        baseUrl: # keep empty to use the server's default URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: AssetShowServer
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
        spectator-metrics: # Reports Spectator Circuit Breaker metrics in the logs
            enabled: false
            # edit spring.metrics.export.delay-millis to set report frequency
